workflows:
  staging-workflow:
    name: Build App for staging
    triggering: {}
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file for build
        script: |
          cd mobile_app
          echo "# Environment variables for Codemagic build" > .env
          echo "API_BASE_URL=$apiBaseUrl" >> .env
          echo "MNOTIFY_API_KEY=$MNOTIFY_API_KEY" >> .env
          echo "MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID" >> .env
          echo "MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL" >> .env
          echo "APP_ENV=$BUILD_ENV" >> .env
          echo "IMAGE_BASE_URL=$IMAGE_BASE_URL" >> .env
          echo "Created .env file for Codemagic build"
          cat .env
      - name: Get Flutter dependencies
        script: |
          cd mobile_app
          flutter packages pub get
      - name: Debug build configuration
        script: |
          cd mobile_app
          echo "Checking build.gradle.kts content:"
          echo "Line 30: $(sed -n '30p' android/app/build.gradle.kts)"
          echo "All minSdk occurrences:"
          grep -n "minSdk" android/app/build.gradle.kts || echo "No minSdk found"
          echo "All minSdkVersion occurrences:"
          grep -n "minSdkVersion" android/app/build.gradle.kts || echo "No minSdkVersion found"
      - name: Clean Flutter project
        script: |
          cd mobile_app
          flutter clean
      - name: Flutter analyze
        script: |
          cd mobile_app
          flutter analyze || echo "Flutter analyze found issues, but continuing build..."
      - name: Flutter Integration tests
        script: |
          cd mobile_app
          flutter test \
            --dart-define=API_BASE_URL=$apiBaseUrl \
            --dart-define=MNOTIFY_API_KEY=$MNOTIFY_API_KEY \
            --dart-define=MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL \
            --dart-define=MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID \
            --dart-define=IMAGE_BASE_URL=$IMAGE_BASE_URL \
            --dart-define=FLUTTER_ENV=$BUILD_ENV
      - name: Build APK
        script: |
          cd mobile_app
          flutter build apk --profile \
            --dart-define=API_BASE_URL=$apiBaseUrl \
            --dart-define=MNOTIFY_API_KEY=$MNOTIFY_API_KEY \
            --dart-define=MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL \
            --dart-define=MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID \
            --dart-define=IMAGE_BASE_URL=$IMAGE_BASE_URL \
            --dart-define=FLUTTER_ENV=$BUILD_ENV
      - name: Build iOS
        script: |
          cd mobile_app
          flutter build ios --profile --no-codesign \
            --dart-define=API_BASE_URL=$apiBaseUrl \
            --dart-define=MNOTIFY_API_KEY=$MNOTIFY_API_KEY \
            --dart-define=MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL \
            --dart-define=MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID \
            --dart-define=IMAGE_BASE_URL=$IMAGE_BASE_URL \
            --dart-define=FLUTTER_ENV=$BUILD_ENV
    artifacts:
      - mobile_app/build/**/outputs/**/*.apk
      - mobile_app/build/**/outputs/**/*.aab
      - mobile_app/build/ios/iphoneos/Runner.app
    publishing:
      scripts:
        - name: Build completion notification
          script: |
            echo "Staging build completed successfully!"
            echo "Artifacts generated in mobile_app/build/"

  production-workflow:
    name: Production Build Workflow
    triggering: {}
    environment:
      vars:
        # These values will be overridden by GitHub Actions
        CUSTOM_MESSAGE: "Default production build"
        BUILD_ENV: "production"
        MNOTIFY_API_BASE_URL: "placeholder"
        MNOTIFY_SENDER_ID: "placeholder"
        MNOTIFY_API_KEY: "placeholder"
        apiBaseUrl: "placeholder"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file for production build
        script: |
          cd mobile_app
          echo "# Environment variables for Production Codemagic build" > .env
          echo "API_BASE_URL=$apiBaseUrl" >> .env
          echo "MNOTIFY_API_KEY=$MNOTIFY_API_KEY" >> .env
          echo "MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID" >> .env
          echo "MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL" >> .env
          echo "APP_ENV=$BUILD_ENV" >> .env
          echo "IMAGE_BASE_URL=$IMAGE_BASE_URL" >> .env
          echo "Created .env file for Production Codemagic build"
          cat .env
      - name: Get Flutter dependencies
        script: |
          cd mobile_app
          flutter packages pub get
      - name: Debug build configuration
        script: |
          cd mobile_app
          echo "Checking build.gradle.kts content:"
          echo "Line 30: $(sed -n '30p' android/app/build.gradle.kts)"
          echo "All minSdk occurrences:"
          grep -n "minSdk" android/app/build.gradle.kts || echo "No minSdk found"
          echo "All minSdkVersion occurrences:"
          grep -n "minSdkVersion" android/app/build.gradle.kts || echo "No minSdkVersion found"
      - name: Clean Flutter project
        script: |
          cd mobile_app
          flutter clean
      - name: Flutter analyze
        script: |
          cd mobile_app
          flutter analyze || echo "Flutter analyze found issues, but continuing build..."
      - name: Flutter integration tests
        script: |
          cd mobile_app
          flutter test \
            --dart-define=API_BASE_URL=$apiBaseUrl \
            --dart-define=MNOTIFY_API_KEY=$MNOTIFY_API_KEY \
            --dart-define=MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL \
            --dart-define=MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID \
            --dart-define=IMAGE_BASE_URL=$IMAGE_BASE_URL \
            --dart-define=FLUTTER_ENV=$BUILD_ENV
      - name: Build app bundle (Release)
        script: |
          cd mobile_app
          flutter build appbundle --release \
            --dart-define=API_BASE_URL=$apiBaseUrl \
            --dart-define=MNOTIFY_API_KEY=$MNOTIFY_API_KEY \
            --dart-define=MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL \
            --dart-define=MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID \
            --dart-define=IMAGE_BASE_URL=$IMAGE_BASE_URL \
            --dart-define=FLUTTER_ENV=$BUILD_ENV
      - name: Build iOS (Release)
        script: |
          cd mobile_app
          flutter build ios --release --no-codesign \
            --dart-define=API_BASE_URL=$apiBaseUrl \
            --dart-define=MNOTIFY_API_KEY=$MNOTIFY_API_KEY \
            --dart-define=MNOTIFY_API_BASE_URL=$MNOTIFY_API_BASE_URL \
            --dart-define=MNOTIFY_SENDER_ID=$MNOTIFY_SENDER_ID \
            --dart-define=IMAGE_BASE_URL=$IMAGE_BASE_URL \
            --dart-define=FLUTTER_ENV=$BUILD_ENV
    artifacts:
      - mobile_app/build/**/outputs/**/*.apk
      - mobile_app/build/**/outputs/**/*.aab
      - mobile_app/build/ios/iphoneos/Runner.app
    publishing:
      scripts:
        - name: Production build completion notification
          script: |
            echo "Production build completed successfully!"
            echo "Release artifacts generated in mobile_app/build/"
