class JarGroups {
  static const List<String> groups = [
    'Funeral',
    'Parties',
    'Trips',
    'Weddings',
    'Saving Groups',
    'Church Contributions',
    'Alumni Dues',
    'Family Support Fund',
    'Community Development',
    'Charity & Donations',
    'Investment Clubs',
    'Emergency Fund',
    'Rent Support',
    'Business Partner Contributions',
    'Susu Collections',
    'Naming Ceremonies',
    'Birthdays',
    'Graduations',
    'Anniversaries',
    'Baby Showers',
    'Engagements',
    'Corporate Events',
    'Cultural Festivals',
    'Reunions',
    'Housewarming',
    'Sports Teams',
    'School Projects',
    'Medical Support',
    'Volunteer Initiatives',
    'Church Offerings',
    'Church Tithes',
    'Scholarship Fund',
    'Startup Fundraising',
    'Loan Repayment Group',
    'Staff Welfare Fund',
    'Retirement Celebration',
    'Naming & Outdooring',
    'Disaster Relief Fund',
    'Community Cleanup',
    'Youth Empowerment Projects',
    'Other',
  ];
}
