/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    shops: Shop;
    batches: Batch;
    products: Product;
    categories: Category;
    stock: Stock;
    suppliers: Supplier;
    customers: Customer;
    services: Service;
    orders: Order;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    shops: ShopsSelect<false> | ShopsSelect<true>;
    batches: BatchesSelect<false> | BatchesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    stock: StockSelect<false> | StockSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullName: string;
  countryCode: string;
  phoneNumber: string;
  role?: ('admin' | 'vendor' | 'shop_attendant') | null;
  rolePermissions?:
    | (
        | 'user_shop_management'
        | 'product_service_inventory_management'
        | 'sales_orders'
        | 'refunds'
        | 'expense_management'
        | 'reporting'
        | 'transactions'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops".
 */
export interface Shop {
  id: string;
  name: string;
  location: string;
  owner: string | User;
  shopType?: ('retail' | 'wholesale' | 'service') | null;
  shopCategory?:
    | (
        | 'grocery'
        | 'electronics'
        | 'clothing'
        | 'pharmacy'
        | 'hardware'
        | 'furniture'
        | 'automotive'
        | 'beauty_personal_care'
        | 'sports_outdoors'
        | 'toys_games'
        | 'books_stationery'
        | 'pet_supplies'
        | 'home_garden'
        | 'health_wellness'
        | 'barbering'
        | 'other'
      )
    | null;
  currency: 'GHS' | 'USD' | 'EUR' | 'GBP' | 'NGN' | 'ZAR';
  countryCode: string;
  contactNumber: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: string;
  /**
   * Select the shop associated with this stock entry.
   */
  shop: string | Shop;
  batchNumber: string;
  expiryDate: string;
  /**
   * This field is automatically updated based on the product inventory from stock updates.
   */
  quantity?: number | null;
  stockAlert: number;
  product?: (string | null) | Product;
  /**
   * The status of the service.
   */
  status?: ('active' | 'inactive') | null;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  shop: string | Shop;
  /**
   * Upload an image for the product
   */
  image?: (string | null) | Media;
  /**
   * A color code for the category, e.g., #FF5733 for red.
   */
  color?: string | null;
  name: string;
  barcode: string;
  category: string | Category;
  description?: string | null;
  prodSellingType: 'retail' | 'wholesale';
  /**
   * e.g. Bottle, Piece, Bowl Pack, Box, etc.
   */
  unit?: string | null;
  /**
   * e.g. 1 pack = 12 bottles
   */
  quantityPerWholesaleUnit?: number | null;
  costPricePerUnit: number;
  sellingPricePerUnit: number;
  trackInventory?: boolean | null;
  /**
   * Enable this if the product has an expiry date
   */
  trackExpiry?: boolean | null;
  inventory?: {
    /**
     * This field is automatically updated based on the product inventory from stock updates.
     */
    quantity?: number | null;
    /**
     * Alert when stock falls below this level
     */
    stockAlert: number;
  };
  /**
   * Link to batches for inventory and expiry tracking
   */
  batches?: (string | Batch)[] | null;
  status?: ('active' | 'inactive') | null;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * The name of the category, e.g., Electronics, Clothing, etc.
   */
  name: string;
  /**
   * Upload an image for the category. This is optional.
   */
  image?: (string | null) | Media;
  /**
   * A color code for the category, e.g., #FF5733 for red.
   */
  color?: string | null;
  /**
   * A brief description of the category.
   */
  description?: string | null;
  /**
   * The status of the service.
   */
  status?: ('active' | 'inactive') | null;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock".
 */
export interface Stock {
  id: string;
  /**
   * Select the supplier for this stock entry.
   */
  supplier?: (string | null) | Supplier;
  /**
   * Select the shop associated with this stock entry.
   */
  shop: string | Shop;
  /**
   * Select the type of stock entry.
   */
  type: 'transfer' | 'sale' | 'purchase' | 'adjustment' | 'return';
  /**
   * Select the order associated with this stock entry, if applicable.
   */
  orderReference?: (string | null) | Order;
  product: string | Product;
  /**
   * Select the batch associated with this stock entry. Required for products with expiry tracking.
   */
  batch?: string | null;
  /**
   * This will update product inventory and batch quantities automatically.
   */
  quantity: number;
  /**
   * Select the shop from which this stock entry originates.
   */
  fromShop?: (string | null) | Shop;
  /**
   * Select the shop to which this stock entry is being transferred.
   */
  toShop?: (string | null) | Shop;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: string;
  /**
   * The name of the supplier.
   */
  name: string;
  contactInfo: {
    /**
     * Email address of the supplier.
     */
    email?: string | null;
    /**
     * Phone number of the supplier.
     */
    phone: string;
  };
  /**
   * Physical address of the supplier.
   */
  address?: string | null;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Select the shop associated with this order.
   */
  shop: string | Shop;
  items?:
    | {
        /**
         * Select the type of item for this order.
         */
        type: string;
        /**
         * Select the service for this order item.
         */
        service?: (string | null) | Service;
        /**
         * Select the product for this order item.
         */
        product?: (string | null) | Product;
        /**
         * Select a batch for this product. Batches are sorted by expiry date (FIFO - First to expire first).
         */
        batch?: (string | null) | Batch;
        /**
         * Enter the quantity of the product ordered.
         */
        quantity: number;
        /**
         * Enter the price of the product per unit.
         */
        unitPrice: number;
        /**
         * Enter the price of the product at the time of order.
         */
        totalPrice?: number | null;
        /**
         * Check if this item was returned.
         */
        isReturned?: boolean | null;
        /**
         * The name of the product at the time of purchase.
         */
        productMetadataAtPurchase?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * The name of the service at the time of purchase.
         */
        serviceMetadataAtPurchase?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * The batch number and expiry date of the product at the time of purchase.
         */
        batchMetadataAtPurchase?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  disountType?: ('percentage' | 'fixed') | null;
  /**
   * Enter the discount amount for this order.
   */
  discount?: number | null;
  totalCost?: number | null;
  payment: 'paid' | 'partial' | 'un_paid';
  /**
   * Enter the amount paid for this order.
   */
  amountPaid?: number | null;
  /**
   * Enter the date when the full amount is due.
   */
  fullAmountDueOn?: string | null;
  /**
   * Select the payment method for this order.
   */
  paymentMothod?: ('cash' | 'card' | 'mobile-money' | 'bank-transfer') | null;
  /**
   * Select the customer associated with this order.
   */
  customer?: (string | null) | Customer;
  /**
   * The customer details at the time of purchase.
   */
  customerMetadataAtPurchase?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Select the shop associated with this service.
   */
  shop: string | Shop;
  /**
   * Select the category for this service.
   */
  category: string | Category;
  name: string;
  /**
   * A brief description of the service.
   */
  description?: string | null;
  /**
   * Upload an image for the service.
   */
  image?: (string | null) | Media;
  /**
   * A color code for the category, e.g., #FF5733 for red.
   */
  color?: string | null;
  /**
   * The price of the service.
   */
  price: number;
  /**
   * The status of the service.
   */
  status?: ('active' | 'inactive') | null;
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  /**
   * The name of the supplier.
   */
  name: string;
  contactInfo?: {
    /**
     * Email address of the supplier.
     */
    email?: string | null;
    /**
     * Phone number of the supplier.
     */
    phone?: string | null;
  };
  /**
   * The user who created this batch.
   */
  createdBy?: (string | null) | User;
  /**
   * The user who created this batch.
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'shops';
        value: string | Shop;
      } | null)
    | ({
        relationTo: 'batches';
        value: string | Batch;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'stock';
        value: string | Stock;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: string | Supplier;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  countryCode?: T;
  phoneNumber?: T;
  role?: T;
  rolePermissions?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops_select".
 */
export interface ShopsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  owner?: T;
  shopType?: T;
  shopCategory?: T;
  currency?: T;
  countryCode?: T;
  contactNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  shop?: T;
  batchNumber?: T;
  expiryDate?: T;
  quantity?: T;
  stockAlert?: T;
  product?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  shop?: T;
  image?: T;
  color?: T;
  name?: T;
  barcode?: T;
  category?: T;
  description?: T;
  prodSellingType?: T;
  unit?: T;
  quantityPerWholesaleUnit?: T;
  costPricePerUnit?: T;
  sellingPricePerUnit?: T;
  trackInventory?: T;
  trackExpiry?: T;
  inventory?:
    | T
    | {
        quantity?: T;
        stockAlert?: T;
      };
  batches?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  color?: T;
  description?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock_select".
 */
export interface StockSelect<T extends boolean = true> {
  supplier?: T;
  shop?: T;
  type?: T;
  orderReference?: T;
  product?: T;
  batch?: T;
  quantity?: T;
  fromShop?: T;
  toShop?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  address?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  shop?: T;
  category?: T;
  name?: T;
  description?: T;
  image?: T;
  color?: T;
  price?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  shop?: T;
  items?:
    | T
    | {
        type?: T;
        service?: T;
        product?: T;
        batch?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        isReturned?: T;
        productMetadataAtPurchase?: T;
        serviceMetadataAtPurchase?: T;
        batchMetadataAtPurchase?: T;
        id?: T;
      };
  disountType?: T;
  discount?: T;
  totalCost?: T;
  payment?: T;
  amountPaid?: T;
  fullAmountDueOn?: T;
  paymentMothod?: T;
  customer?: T;
  customerMetadataAtPurchase?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}